### ISSUE TITLE
Import error when using @figspec/react

### ISSUE THREAD

**Issue by karanmidha** [pocka/figspec-react#1]
Hi, I was using ^1 of figspec which was working fine. I tried to update to the v2 today and my imports started failing.
This is the error that I am getting. How can we resolve this?

<img width="973" alt="image" src="https://github.com/pocka/figspec-react/assets/21328841/598ff79f-f05c-4f22-bb36-27d347bac1f5">

My import looks like this
`import { FigspecFileViewer } from "@figspec/react";`

@pocka

**Comment by pocka** [comment]
What platform/bundler/transpiler are you using?

**Comment by karanmidha** [comment]
I am using webpack v5.88.0

**Comment by pocka** [comment]
It seems because of the library (`@figspec/components` and `@figspec/react`) files still use extension-less import.
I'll check the configuration later.

**Comment by pocka** [comment]
Published [`@figspec/components@2.0.2`](https://github.com/pocka/figspec/releases/tag/v2.0.2), which adds `.js` to every extension-less import paths.
